### PR TITLE
Fix GitHub Actions build

### PR DESCRIPTION
**Pull request by danyalaytekin**
This pull request mainly fixes the build and introduces me to Pa11y PR creation.

1. [Fixes](https://github.com/pa11y/pa11y.github.io/actions/runs/6395649859/job/17359782763?pr=105) the `make test` step of the GitHub Actions check `checkout_and_test` which [had stopped working recently](https://github.com/pa11y/pa11y.github.io/actions/runs/6324881913/job/17175245657?pr=105) because of the Ubuntu issue [currently affecting pa11y-ci](https://github.com/pa11y/pa11y-ci/issues/198).  It does this by regressing the image from `ubuntu-latest` to `ubuntu-20.04`.  Soon `ubuntu-latest` will return.
1. Makes several other tiny changes, some of which emerged primarily to bump the build, but which hopefully remain useful:
    1. Recommend a VS Code extension for `make`
    1. Add `.nvmrc` and set to same Node.js version as the CI check
    1. Make one instance of the copyright year current; republishing should fix the other instance
    1. Improve consistency where we mention `GitHub` and `GitHub Issues`

If the PR is approved I also plan to rename `master` to `main` a moment before merging it.  This is part of verifying this renaming process before extending it to repos which have more consumers, and in this repo's case it will also republish the site, immediately after it is unpublished by the change of name.

### CODE REVIEW

**Review by jpw — APPROVED** [review]
LGTM! Thank you.

**Comment by danyalaytekin** [comment]
Renaming `master` → `main` now...

**Comment by danyalaytekin** [comment]
Renaming took GitHub about a minute and has not actually unpublished https://pa11y.org (yet?).  Let's see whether the [workflow's mention of `master` will map to `main`](https://github.com/pa11y/pa11y.github.io/blob/main/.github/workflows/build-and-test.yml#L7) after the merge.  There doesn't seem to be a variable like `{{ github.default_branch }}` that would work in the `on:` section of a workflow.

### GitHub's advisories before renaming
GitHub's advisories before renaming (will update PRs, branch protection rule, will unpublish site, will not update clones)

### GitHub's notice once in progress
'Branch master will be renamed to main shortly

### GitHub's notice once complete
GitHub's advice about how to update a local clone

**Comment by danyalaytekin** [comment]
> Let's see whether the [workflow's mention of master will map to main](https://github.com/pa11y/pa11y.github.io/blob/main/.github/workflows/build-and-test.yml#L7) after the merge

It hasn't, so `build_and_test` hasn't run yet on `main`.  Will create another PR for this, and it's good to know about for the other repos.  We can use a temporary `on: push: branches: [master, main]`.

**Pull request merged**
