### PR TITLE
Change the intro para to be friendlier to non devs

### PR DESCRIPTION
**Pull request by typothecary**

### CODE REVIEW

**Comment by hollsk** [comment]
Agree with amending this sentence as I had a papercut moment over "tooling", a _very_ developery word. One concern I have is that there's a tautology in the adjacent sentences, "to help make it better", and "to help... make their web pages more accessible". 

Perhaps we should just bin the "tools and automation" bit entirely and let the second sentence's "free and open source tools" speak for itself?

**Comment by rowanmanning** [comment]
Oh I somehow missed this! Yes I agree with Hollie on the tools and automation. I've been using the first sentence for Twitter/GitHub bios etc, we should probably decide what those should be too.

**Comment by typothecary** [comment]
OK - how about this instead? 

Here at Pa11y, we think making the web more accessible improves it for everyone. So we publish a range of free and open source tools to help designers and developers make their web pages more accessible:

**Comment by rowanmanning** [comment]
I like it 👍👌 @hollsk? Thanks for taking a look Kathleen!

If you have any ideas for a snappy Twitter and GitHub bio then that'd be useful too. Currently they're both:

> Pa11y aims to improve the accessibility of the web through better tooling and automation.

The only limitation is that it has to fit nicely in the header section here: https://github.com/pa11y

**Comment by typothecary** [comment]
@rowanmanning ... ?

> Pa11y aims to improve web accessibility by building free and open source tools

**Comment by hollsk** [comment]
Edit looks great 👍  

Less sure about the one-liner though - looks like an incomplete sentence. Maybe flip the components? 

> Pa11y builds free and open source tools that help improve web accessibility

... but then I'm not sure I like my suggestion because that also looks like an incomplete sentence. The thing with the original was that it had that "_better_ tools and automation", and the qualifier gave it a bit of punch. Without it, the one-liner seems quite wooly and vague :/

Urgh, words are hard

**Comment by typothecary** [comment]
Another go .. 
> Pa11y helps improve web accessibility through better tools and automation

**Comment by hollsk** [comment]
Can we merge this? I'm not sure what we're waiting on!

**Comment by rowanmanning** [comment]
Yeah I think we got side-tracked! I'll merge

**Pull request merged**
